// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherLog.Data;

#nullable disable

namespace WeatherLog.Migrations
{
    [DbContext(typeof(WeatherLogContext))]
    [Migration("20250714151157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("WeatherLog.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AfternoonTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageWind")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicInfo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedInfo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EveningTemp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinTemp")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MorningTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindDirection")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindGust")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
